Repository TinxHQ/wazo-production-sf-jobs, pull requests merged in 2024-05, with the labels that each got.

#34 sibling: remove unused python3.7 mount
  roles/wazo-tox/library/docker_sibling_packages.py
Labels: mergeit

#35 fix encrypted value for mattermost api key
  zuul.d/wazo_secrets.yaml
Labels: mergeit, auto-merge

#36 use docker compose without hyphen command
  roles/wazo-tox/tasks/main.yaml
Labels: mergeit

#37 remove obselete version key for docker compose file
  roles/wazo-tox/library/docker_sibling_packages.py
Labels: auto-merge
